[package]
name = "passwordcheck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.22"
sha1 = "0.10.6"
tokio = { version = "1.33.0", features = ["full"] }
